### ISSUE TITLE
Random HP and no results 

### ISSUE THREAD

**Issue by JulianJ508** [winsomniak/kagero-calc#2] opened 2017-12-31 04:40 UTC
Characters start off with a random number off HP remaining and results against all are not showing...

**Comment by winsomniak** [comment] 2017-12-31 19:47
I can't reproduce this. Possibly a specific browser problem. Please provide as much info as possible.

Thanks

**Comment by winsomniak** [comment] 2018-01-04 17:58
Without being able to reproduce this we can't fix it. Please let us know your browser and os information. Would also be helpful if you provide the steps to reproduce and a screenshot of the javascript console (CTRL + ALT + K) or (CTRL + SHIFT + J)

**Comment by winsomniak** [comment] 2018-01-07 19:49
@JulianJ508 I'm closing this until we know more. Please feel free to re-open if you have more info to provide.

Thanks!

**Closed by winsomniak** 2018-01-07 19:49 UTC
Labels: wontfix
