### ISSUE TITLE
Thani doesn't get "effective against" bonus

### ISSUE THREAD

**Issue by Totaliss** [winsomniak/kagero-calc#70] opened 2018-01-21 20:32 UTC
Title ^
Micaiah's Thani doesn't get the effective against bonus vs armor and cavalry opponents

**Comment by Lorenzooone** [comment] 2018-01-21 20:34
Duplicate of https://github.com/winsomniak/kagero-calc/issues/60
Thanks for reporting, though. The issue's been worked on.

**Comment by Lorenzooone** [comment] 2018-01-21 20:35
Duplicate of https://github.com/winsomniak/kagero-calc/issues/60
The issue's being worked on, thanks for reporting though.

**Closed by Lorenzooone** 2018-01-21 20:34 UTC
Labels: duplicate
